import Head from "next/head";
import { useEffect, useState } from "react";
import axios from "axios";

export default function Home() {

  const [db,setDb] = useState([])

  useEffect(()=>{
    const peticion = async ()=>{
    const endpoint = "http://localhost:8001/productos"
    const respuesta = await axios.get(endpoint)
    const info = await respuesta.data
    
    setDb(info)
  }
  peticion()
},[]
)

  return (
    <>
      <Head>
        <title>Nexo Digital</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
    </>
  );
}
